services:
  web:
    build: .
    environment:
      JAKARTA_PERSISTENCE_JDBC_URL: jdbc:postgresql://db:5432/weather_servlet_app
      JAKARTA_PERSISTENCE_JDBC_USER: postgres
      JAKARTA_PERSISTENCE_JDBC_PASSWORD: postgres
      HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    container_name: weather_servlet_app_db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: weather_servlet_app


    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s